### ISSUE TITLE
mano skeleton joints and openxr standard skeleton joints 

### ISSUE THREAD

**Issue by cavalleria** [lixiny/manotorch#10]
Hi lixiny
I have a question about the mano skeleton joints and the OpenXR standard. We know that mano has 21 skeleton joints (as shown in the first image), but the OpenXR standard has 26 skeleton joints (as shown in the second image). Is there a way to generate the additional 5 skeleton joints based on mano? thanks~~
![image](https://github.com/lixiny/manotorch/assets/13869178/431150b6-36ab-4065-a8ca-148e56061bb8)

![image](https://github.com/lixiny/manotorch/assets/13869178/4d5d6bb4-6a48-48c4-b4a6-6a5c7764bf19)

**Comment by lixiny** [comment]
Since the MANO model does not provide additional degrees of freedom on the four carpometacarpal joints (excluding the thumb), adding such joints would not alter the forward kinematics of MANO; therefore, I believe that adding these four corresponding points is not helpful.

Best,
Lixin
