### ISSUE TITLE
Vertex region id

### ISSUE THREAD

**Issue by ZhaoLizz** [lixiny/manotorch#13]
Hi! According to the following image, it seems you assign each vertex with a region id to define the 17 diffrent regions. However, I cannot find the vertex_to_region mapping assets. Can you kindly explain how to get region_id of each vertex? Thanks in advance!

<img width="343" alt="image" src="https://github.com/lixiny/manotorch/assets/29300861/804f04df-2f16-4e7c-bd69-ea00c0424622">

**Comment by ZhaoLizz** [comment]
Dose the `merged_vertex_assignment.txt` define the vertex_to_region mapping?

**Comment by lixiny** [comment]
`> Dose the merged_vertex_assignment.txt define the vertex_to_region mapping?`

Right,  
the row number is the index of vertex defined in MANO hand model, and the corresponding integer is the region assignment for this vertex. 

Best, 
Lixin

**Comment by ZhaoLizz** [comment]
Thanks for the comment.
