### ISSUE TITLE
anatomical constraints.

### ISSUE THREAD

**Issue by ECNUHP** [lixiny/manotorch#2]
Your outstanding research work is wonderful!

I am trying to obtain the parameters of mano with optimization method(LM)

But the optimized joint_rotation and shape_parameter are very weird, unnatural. I see that you mentioned anatomical constraints.
 _avoid hand pose abnormality during learning or fitting by applying anatomically constraints on rotation axes and angles._

I am very interested. Could you share relevant informations or papers for anatomical constraints.

Thank you

**Comment by lixiny** [comment]
Thanks for your interest in our work!

The paper related to **anatomically constraint** can be found at [CPF](https://arxiv.org/abs/2012.00924). And the code at [here](https://github.com/lixiny/CPF).

Best, 
Lixin
