### ISSUE TITLE
IK issues

### ISSUE THREAD

**Issue by cavalleria** [lixiny/manotorch#6]
Hi @lixiny , thanks for your great work! Is this method helpful for solving ik? I solve hand joints rotation according to [Hybrik](https://openaccess.thecvf.com/content/CVPR2021/papers/Li_HybrIK_A_Hybrid_Analytical-Neural_Inverse_Kinematics_Solution_for_3D_Human_CVPR_2021_paper.pdf) method, but it has abnormal pose when the axis angle is close to zero.

**Comment by lixiny** [comment]
Unfortunately, this package only performs the forward kinematics. 

Best,
Lixin
