### ISSUE TITLE
Question about the transformation between original MANO and A-MANO

### ISSUE THREAD

**Issue by zdchan** [lixiny/manotorch#9]
Hi, I just want to ask that, with AxisLayerFK.compose I can transfer anatomy aligned euler angles to original mano pose. Is there anyway back?

**Comment by lixiny** [comment]
There is an indirect approach available, 

which involves mapping the original **mano pose** `cure_pose` (in the form of axis angle) to `T_g_p` (16 SE3 transformation matrices, all base on the global 'world' coord. sys.), 
and then transforming it into the anatomy aligned euler angles `ee` through `axisFK`. 

![image](https://github.com/lixiny/manotorch/assets/32672902/7c2d4179-1e8d-474a-96f8-cd7cd7568e29)


The `ee` is subsequently used for loss evaluation. However, it can also be re-composed this process as needed.


Lixin.
